app: 
  name: "web"
  mode: "dev"
  port: 80

log: 
 level: "debug"
 filename: "web.log"
 max.size: 200
 max_backups: 7

mysql:
 host: "10.161.43.251"
 port: 3306
 user: "root"
 password: "123456"
 dbname: "super_computer"
 max_open_conns: 200
 max_idle_conns: 50
